// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLGCNxey72mcdTANr2lnVD-dwd8F6yzWQ',
    appId: '1:839560434513:web:efc4e059a78d4a9f49b970',
    messagingSenderId: '839560434513',
    projectId: 'smart-campus-asst-8391',
    authDomain: 'smart-campus-asst-8391.firebaseapp.com',
    storageBucket: 'smart-campus-asst-8391.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1-d68ciDW0N_sW2Ko4P-uQwznvSWW6Uk',
    appId: '1:839560434513:android:96f50b42865d3d4f49b970',
    messagingSenderId: '839560434513',
    projectId: 'smart-campus-asst-8391',
    storageBucket: 'smart-campus-asst-8391.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDgHyJoNeR2Y5zbMizC31JXXN4Zp_RFJw',
    appId: '1:839560434513:ios:76bf1236fae2cbde49b970',
    messagingSenderId: '839560434513',
    projectId: 'smart-campus-asst-8391',
    storageBucket: 'smart-campus-asst-8391.firebasestorage.app',
    iosBundleId: 'com.abdelrahmantamer.smartcampus',
  );

}